### ISSUE TITLE
Normalize string lengths used in variable parameters sent to SQL Server

### ISSUE THREAD

**Issue by kramer1007** [akkadotnet/Akka.Persistence.SqlServer#159]
I would like to see if the project would normalize the string lengths that are generated on the queries sent to SQL Server. This will reduce plan cache generation/bloat on the SQL server side of things.

Example: this is one of the delete queries sent over to the database from the application:
```
(@PersistenceId nvarchar(91),@ToSequenceNr bigint)
                DELETE FROM dbo.EventJournal
                WHERE PersistenceId = @PersistenceId AND SequenceNr <= @ToSequenceNr;
                DELETE FROM dbo.Metadata
                WHERE PersistenceId = @PersistenceId AND SequenceNr <= @ToSequenceNr;
```

This is what it should look like to properly match the database column size type:
```
(@PersistenceId nvarchar(255),@ToSequenceNr bigint)
                DELETE FROM dbo.EventJournal
                WHERE PersistenceId = @PersistenceId AND SequenceNr <= @ToSequenceNr;
                DELETE FROM dbo.Metadata
                WHERE PersistenceId = @PersistenceId AND SequenceNr <= @ToSequenceNr;
```

The first one shows 91 due to the built-in C# library auto-sizing to the length of the data in question versus using the length of the field. This causes multiple SQL Server query plans to be generated since there could be multiple lengths of the string parameter.

Here is a link to what you can do to query this when testing: https://www.brentozar.com/blitzcache/multiple-plans/

I'm sure there's a few ways to change QueryExecutor.cs to fix this. I'm not C# expert myself. I'm attacking this from a DBA's perspective.

**Comment by IgorFedchenko** [comment]
Yeah, I guess this is doable - we can check current SQL schema and set parameter size to the column size explicitly for `nvarchar` fields.

I think we can/should do that for all SQL plugins, so I will give this idea a try in the main Akka.NET repo.

**Comment by IgorFedchenko** [comment]
We are not wanting for the next release of Akka.NET to test and merge second PR attached to this issue. This should fix the problem.
