### ISSUE TITLE
Occasional huge spikes when executing batches using BatchingSqlJournal

### ISSUE THREAD

**Issue by object** [akkadotnet/Akka.Persistence.SqlServer#190]
I came across this behavior while investigating https://github.com/akkadotnet/akka.net/issues/4265

Scenario: load testing Akka persistent actors state recovery. Sent 1500 message to persistent actors running in a cluster deployed on two VMs.

- On the first node all actors state was successfully recovered, logs show that it usually took just a few milliseconds to recover actor state.
- On the second VM recovery time suddenly increased from a few millisecond to a few seconds to 1-3 minutes. Then after couple of minutes it dropped back to normal. Here's an extract from logs:

09:40:37.747	Completed batch (chunkId: 14) of 1 operations in 344.318 milliseconds
09:40:37.747	Completed batch (chunkId: 15) of 1 operations in 345.5932 milliseconds
09:40:37.747	Completed batch (chunkId: 10) of 1 operations in 352.9699 milliseconds
09:40:37.747	Completed batch (chunkId: 6) of 1 operations in 308.9335 milliseconds
09:40:37.504	Completed batch (chunkId: 23) of 1 operations in 209.1461 milliseconds
09:40:37.504	Completed batch (chunkId: 25) of 1 operations in 192.1565 milliseconds
09:40:37.504	Completed batch (chunkId: 24) of 1 operations in 189.5346 milliseconds
09:40:37.504	Completed batch (chunkId: 22) of 1 operations in 207.0679 milliseconds
09:40:37.500	Completed batch (chunkId: 25) of 1 operations in 189.0474 milliseconds
--> End of spike
09:40:37.278	Completed batch (chunkId: 60) of 1 operations in 41404.872 milliseconds
09:40:36.434	Completed batch (chunkId: 0) of 1 operations in 119757.1183 milliseconds
09:40:36.434	Completed batch (chunkId: 33) of 1 operations in 200954.4958 milliseconds
09:38:37.567	Completed batch (chunkId: 3) of 1 operations in 82002.7628 milliseconds
09:38:37.567	Completed batch (chunkId: 0) of 1 operations in 82023.2096 milliseconds
09:38:37.567	Completed batch (chunkId: 10) of 1 operations in 82034.635 milliseconds
09:38:37.567	Completed batch (chunkId: 13) of 1 operations in 82039.9989 milliseconds
09:38:37.567	Completed batch (chunkId: 5) of 1 operations in 81991.5412 milliseconds
--> Start of spike
09:37:15.349	Completed batch (chunkId: 36) of 1 operations in 1306.1355 milliseconds
09:37:15.350	Completed batch (chunkId: 35) of 1 operations in 1314.7566 milliseconds
09:37:15.350	Completed batch (chunkId: 29) of 1 operations in 1324.6597 milliseconds
09:37:15.351	Completed batch (chunkId: 17) of 1 operations in 1337.0179 milliseconds
09:37:15.350	Completed batch (chunkId: 31) of 1 operations in 1299.3127 milliseconds

**Comment by object** [comment]
Suggestions from gitter:

- You may or may not want to try logging some threadpool metrics to see whether there's some form of contention going on. This helped us trobleshoot issues where a misconfigured grafana dependency was causing pool explosions when actors would start up/shut down
 ThreadPool.GetAvailableThreads(out int avWt, out int avIot);
 ThreadPool.GetMaxThreads(out int maxWt, out int maxIot);
 var (workerThreads,ioThreads)= (maxWt - avWt,maxIot-avIot); //log this every second
- If you can enable MVCC (i.e. Enable snapshot Isolation and default isolation level READ_COMMITTED_SNAPSHOT) that could help
- Might be worth logging the SQL executed in the chunk
- Mayyyybe try adding some code in the batching process so that if there's only READ commands in the batch, a transaction isn't used.
- If you're feeling adventurous, you may want to try (it is technically prerelease state) the Linq2db plugin which is based on akka-persistence-jdbc. Code is the branch in akkadotnet/Akka.Persistence.Linq2Db#10 and I have it as a nuget package here. Configuring for 'compatibility mode' (Where it should be both backward and forward compatible with Existing Journal/snapshot) is exampled here. I've been running the journal in not-quite-prod (i.e. syncing data with old system) for a few months now with great success

**Comment by Arkatufus** [comment]
@object can you confirm that this is still happening with the new batching code we introduced back in May?

**Comment by object** [comment]
@Arkatufus I haven't migrated our code to use new batching code but plan to do it soon. I will run then some tests and update the issue.

**Comment by ingted** [comment]
This is still happening with 1.5.0!!

**Comment by Aaronontheweb** [comment]
@ingted @object I'd consider taking a look at Akka.Persistence.Sql, now that it's RTMed: https://github.com/akkadotnet/Akka.Persistence.Sql

**Comment by Aaronontheweb** [comment]
It's faster than batchingsqljnournal anyway: https://github.com/akkadotnet/Akka.Persistence.Sql/blob/dev/docs/articles/benchmarks.md

**Comment by ingted** [comment]
Let me try try see!!

**Comment by object** [comment]
Absolutely! We are going to try it shortly.

**Comment by object** [comment]
@Aaronontheweb BTW what about Akka.Persistence.Query and Akka.Persistence.Query.Sql? Akka Streams is still based on them, correct?

**Comment by Aaronontheweb** [comment]
@object that's correct - the namespaces are different for Akka.Persistence.Sql but otherwise they work identically. You can follow my upgrade tutorial to see all the steps I had to perform in order to upgrade: https://www.youtube.com/watch?v=gSmqUrVHPq8

**Comment by object** [comment]
@Aaronontheweb Thank you. In the video you talk about two strategies, and the recommended one requires schema upgrade. Would it be reasonable to first upgrade in compatibility mode and verify that things are okay and then upgrade the schema on a next stage?

**Comment by Aaronontheweb** [comment]
@object absolutely - the schema upgrade basically just adds support for better performing tag queries and the anti-corruption layer. You can upgrade without either of those.

**Comment by object** [comment]
We have succesfully migrated our code to use the new Akka.Persistence.Sql. I am closing this issue.

**Comment by Aaronontheweb** [comment]
> We have succesfully migrated our code to use the new Akka.Persistence.Sql. I am closing this issue.

And it's working well?!

**Comment by object** [comment]
So far so good. Testing in Stage.

**Comment by object** [comment]
@Aaronontheweb One minor observation. We had to explicitly set the class name in HOCO (still using HOCON):

```
    journal {
      plugin = "akka.persistence.journal.sql"
      sql {
        class = "Akka.Persistence.Sql.Journal.SqlWriteJournal, Akka.Persistence.Sql"
        provider-name = "LinqToDB.ProviderName.SqlServer2019"
        auto-initialize = off
        table-mapping = "sql-server"
        tag-write-mode = Csv
        delete-compatibility-mode = true
      }
      sql-server {
        schema-name = dbo
        table-name = EventJournal
      }
    }

```
Not the line **class = "Akka.Persistence.Sql.Journal.SqlWriteJournal, Akka.Persistence.Sql"**. Without it the exception was raised about missing class in plugin. Your video and migration guide doesn't mention class name as mandatory field.
