### ISSUE TITLE
SqlServerPersistence.Init is missing -- Documentation out of date?

### ISSUE THREAD

**Issue by BrainSlugs83** [akkadotnet/Akka.Persistence.SqlServer#21]
Hey guys,

It looks like in 1.0.5 and on "SqlServerPersistence.Init" is missing -- and there's no documented way to initialize this extension.

The README for this repo still says that this is the correct way to initialize the extension. -- Please update the readme, because whatever the new method is, it's not clear, and it means we can't use a newer version than 1.0.4. :(

**Comment by alexvaluyskiy** [comment]
We should close it
