### ISSUE TITLE
Add Test for ClusterConfigSpec

### ISSUE THREAD

**Issue by Danthar** [akkadotnet/Akka.Persistence.SqlServer#25]
In order to prevent bugs when the default config changes, every persistence plugin should have an implementation of this Test:

https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Cluster.Tests/ClusterConfigSpec.cs

**Comment by alexvaluyskiy** [comment]
Fixed https://github.com/akkadotnet/Akka.Persistence.SqlServer/pull/29
