### ISSUE TITLE
journaling and sqlexceptions - PK violations 

### ISSUE THREAD

**Issue by VaclavK** [akkadotnet/Akka.Persistence.SqlServer#50]
using 1.1.5 pre-release version of the plugin but the issue was seen with earlier versions too

an example - 
Rejected to persist event type ["BrokerDealer.Contracts.Messages.MessageHandled"] with sequence number [59] for persistenceId ["/user/CashFundingManagementView/$Gb"] due to ["Violation of PRIMARY KEY constraint 'PK_AKKAJournal'. Cannot insert duplicate key in object 'dbo.AKKAJournal'. The duplicate key value is (/user/CashFundingManagementView/$Gb, 59).

I see higher incidence of this with higher actor instance count

what we do is very simple - every incoming message is persisted into the journal and when the message is handled the corresponding MessageHandled is appended to the journal - this allows us to only replay messages that have not yet been processed

I see sufficient time span between original message under certain persistence id and sequence number and the exception e.g. 

this is the exception from the log (note the TS)

2016-09-21 10:34:42.843 +01:00 [Warning] Rejected to persist event type ["BrokerDealer.Contracts.Messages.Feed.CashManager.GrossFlow"] with sequence number [8] for persistenceId ["/user/CashFundingManagementView/$h"] due to ["Violation of PRIMARY KEY constraint 'PK_AKKAJournal'. Cannot insert duplicate key in object 'dbo.AKKAJournal'. The duplicate key value is (/user/CashFundingManagementView/$h, 8).

this is the original journal entry
SELECT [PersistenceID]
      ,[SequenceNr]
      ,[Timestamp]
      ,[IsDeleted]
      ,[Manifest]
      ,[Payload]
      ,[Tags]
  FROM [BrokerDealer].[dbo].[AKKAJournal] where PersistenceID='/user/CashFundingManagementView/$h' and SequenceNr=8

I have removed the payload for brewity

```
PersistenceID   SequenceNr  Timestamp   IsDeleted   Manifest
```

1   /user/CashFundingManagementView/$H  8   636100472666516918  0   BrokerDealer.Contracts.Messages.Feed.CashManager.GrossFlow, BrokerDealer.Contracts

unix timestamp converts to 2016-09-21​T09:34:26.651Z (vs the exception time of 2016-09-21 10:34:42.843 +01:00

We are aware of the fact that this is pre-release so I would also like to ask  for suggestions re alternative approach/other akka persistance plugin implementations that would behave stable

**Comment by VaclavK** [comment]
I was able to spot particular instance of this issue and see that this (seems to be/is) caused by naming collisions of the agents with SQL being case insensitive.

e.g. it failed to insert following composite key into journal (note the casing of the last path token) - (/user/CashFundingManagementView/$H, 1) 

the following was the contents of the journal table 

/user/CashFundingManagementView/$c	1
/user/CashFundingManagementView/$F	1
/user/CashFundingManagementView/$G	1
/user/CashFundingManagementView/$h	1
/user/CashFundingManagementView/$I	1
/user/CashFundingManagementView/$J	1
/user/CashFundingManagementView/$K	1
/user/CashFundingManagementView/$M	1
/user/CashFundingManagementView/$N	1
/user/CashFundingManagementView/$v	1
/user/CashFundingManagementView/$w	1
/user/CashFundingManagementView/$x	1

when of course the following would have proved the collision, again note the casing (SELECT [PersistenceID]
      ,[SequenceNr]
      ,[Timestamp]
      ,[IsDeleted]
      ,[Manifest]
      ,[Payload]
      ,[Tags]
  FROM [BrokerDealer].[dbo].[AKKAJournal] where PersistenceID='/user/CashFundingManagementView/$H')


can we override the naming strategy (I need yet to check doc on this but I do not believe I have seen that option anywhere). I have to say that I would have personally preferred straightforward numbering e.g. /user/CashFundingManagementView/$1, /user/CashFundingManagementView/$2 etc. More on that, I do not believe that the plugin doc would state that case sensitive collation would be required so I am not sure whether this is documentation problem or oversight in design/implementation of the plugin.

I also raised performance defect associated with journalling and believe that these requests failing would have role in that ( - any comment on that?

**Comment by Horusiath** [comment]
Why are you using anonymous actors (with generated names) instead of simply naming them on the first place? Also why are you using actor path as it's PersistenceId?

**Comment by VaclavK** [comment]
good ideas...we have done that for clarity/visibility and also as we plan to heavily distribute so we believe we would need to be able to tell which logical deployment it belongs to

seems like you would recommend different strategy?

fixed the issue now with making the column as Case sensitively collated

**Comment by Horusiath** [comment]
If you'll create a persistenceId based on anonymously generated actor name, you may find a hard time to send a message to it later, when you'll try to recreate it on another machine in different order than originally.

Usually domain aggregates have natural identifiers used by the business logic (user emails, account numbers etc.). Optionally it's just any identifier that is assigned once to an aggregate / entity / persistent actor and used to recognize it among all others for all the time.
