### ISSUE TITLE
performance of journal write process

### ISSUE THREAD

**Issue by VaclavK** [akkadotnet/Akka.Persistence.SqlServer#51]
using version 1.1.5 pre-release but was seen with other versions a well

we run our standartised test with 5000 incoming messages and test actor system performance under various settings (journal and snapshot enabled)

in all tests we see lot of synchronisation/high SQL time spent around journal write
mosts test would spend 120 seconds in total just journalling these messages 

to be precise it is journalling 10000 message as we also journal MessageHandled for each incoming message when it was actually processed

based on the data, there seems to be synchronization/ async wait bottleneck in journal write routine where system is under no real particular stress (low CPU etc.)

see the snippet from the ANTS profiles

![sql bug 41](https://cloud.githubusercontent.com/assets/3881864/18707411/d7efa98e-7fed-11e6-9ae6-de198e514628.PNG)

also note the level of wait callstack (over 30K invocations deep) consisting System.Threading.ThreadPoolWorkQueue.Dispatch()  
 and Method 
System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()   nested over and over
see the comparision over wait time over actual execution vs the inserts themselves and their timing

![sql bug 41_2](https://cloud.githubusercontent.com/assets/3881864/18707463/1be6cac8-7fee-11e6-91cd-5f4012619624.PNG)

the dabatase server is under no stress and within our actor we do our own upserts of business data derived from incoming messages with much higher throughput

with increased number of instances of the actor, the insert into journal gets considerably slower and journal would start throwing lot of PK violation exceptions (https://github.com/akkadotnet/Akka.Persistence.SqlServer/issues/50) 

the HOCON is here (passwords removed)

<akka>
    <hocon>
      <![CDATA[
          akka {
            # here we are configuring log levels
            log-config-on-start = on
            stdout-loglevel = INFO
            loglevel = DEBUG
            loggers = ["Akka.Logger.Serilog.SerilogLogger, Akka.Logger.Serilog"]
             persistence
            {
             journal 
             {
              plugin = "akka.persistence.journal.sql-server"

```
            sql-server 
            {
              # qualified type name of the SQL Server persistence journal actor
              class = "Akka.Persistence.SqlServer.Journal.SqlServerJournal, Akka.Persistence.SqlServer"

              # dispatcher used to drive journal actor
              plugin-dispatcher = "akka.actor.default-dispatcher"

              # connection string used for database access
              connection-string = REMOVED"

              # default SQL commands timeout
              connection-timeout = 30s

              # SQL server schema name to table corresponding with persistent journal
              schema-name = dbo

              # SQL server table corresponding with persistent journal
              table-name = AKKAJournal

              # should corresponding journal table be initialized automatically
              auto-initialize = off

              # timestamp provider used for generation of journal entries timestamps
              timestamp-provider = "Akka.Persistence.Sql.Common.Journal.DefaultTimestampProvider, Akka.Persistence.Sql.Common"

              # metadata table
              metadata-table-name = AKKAMetadata
            }
         }
         snapshot-store 
         {
           plugin = "akka.persistence.snapshot-store.sql-server"

            sql-server 
            {

                # qualified type name of the SQL Server persistence journal actor
                class = "Akka.Persistence.SqlServer.Snapshot.SqlServerSnapshotStore, Akka.Persistence.SqlServer"

                # dispatcher used to drive journal actor
                plugin-dispatcher = "akka.actor.default-dispatcher"

                # connection string used for database access
                connection-string = "REMOVED*"

                # default SQL commands timeout
                connection-timeout = 30s

                # SQL server schema name to table corresponding with persistent journal
                schema-name = dbo

                # SQL server table corresponding with persistent journal
                table-name = AKKASnapshot

                # should corresponding journal table be initialized automatically
                auto-initialize = off
            }
         }
      }
        # this config section will be referenced as akka.actor
        actor {

serializers {
  wire = "Akka.Serialization.WireSerializer, Akka.Serialization.Wire"
}
serialization-bindings {
  "System.Object" = wire
}
          provider = "Akka.Remote.RemoteActorRefProvider, Akka.Remote"
          debug {
              receive = on
              autoreceive = on
              lifecycle = on
              event-stream = on
              unhandled = on
          }
          deployment {
          /CashFundingManagementView {
            router = round-robin-pool
            nr-of-instances = 100
            }
          }
        }
        # here we're configuring the Akka.Remote module
        remote {
          helios.tcp {
              transport-class =
        "Akka.Remote.Transport.Helios.HeliosTcpTransport, Akka.Remote"
              #applied-adapters = []
              transport-protocol = tcp
              port = 7095
              hostname = "localhost"
          }
        log-remote-lifecycle-events = INFO           
      }
  ]]>
</hocon>
```

**Comment by VaclavK** [comment]
this kind of overlaps with 50 -

I see separate connection open for reading of highest sequence number... why not reuse connection if within the write message flow?

**Comment by Horusiath** [comment]
Thanks for the info. For the performance issues we need to prepare some perf benchmarking (maybe NBench tests). Any help of that field will be really appreciated.

> I see separate connection open for reading of highest sequence number... why not reuse connection if within the write message flow?

Do you mean separate db requests during the recovery phase? I don't recall reading highest sequence nr during writes.

Also this code is not tailored for MS SQL only - it's using an Akka.Persistence.Sql.Common in it's core. Could you precise how basic identity type would help with querying data tied to specific persistence ids?

**Comment by VaclavK** [comment]
running some more tests... we see considerable performance degradation with SQL journal vs. in memory.. obviously SQL would not be as fast as memory but with sufficiently performant SQL server (as we have) and large number of actors (to process persistence/write messages) we would expect degradation to be much less... at the moment we see most CPU time spend in AKKA (Journal) plumbing as opposed to actor itself (see screenshot)

![sql bug 41_4](https://cloud.githubusercontent.com/assets/3881864/18792538/daf9d3e4-81ae-11e6-9b78-809afe496312.PNG)

![sql bug 41_5](https://cloud.githubusercontent.com/assets/3881864/18792548/dfff4c2a-81ae-11e6-8807-b1de1cff74d4.PNG)

very little is spent for the business process itself... any comments/ideas?

**Comment by andreyleskov** [comment]
Hi all, one more vote for this issues, as after updating to Akka.Persistence.SqlServer 1.1.2 
performance greatly decreased 8 (
