### ISSUE TITLE
Snapshots not getting played back

### ISSUE THREAD

**Issue by suganthkumar** [akkadotnet/Akka.Persistence.SqlServer#65]
I have created a sample application, which creates a snapshot every 25 events and removes all event messages until that time. But when it reload the actor, only the events are recovered and not the snapshot.

i am using the Akka.Persistence.SqlServer version 1.1.1.7-beta and Akka.Persistence.Sql.Common version 1.2.0.36-beta.

I have also observed that the metadata table never get any records... not sure whether its part of design.

**Comment by Horusiath** [comment]
Metadata table is used only to remember the latest sequence number in case if you've deleted the latest known event, so it only should be filled in that case.

Regarding snapshots, could you show the actor code? Are you sure that you're waiting for the snapshot to be stored? Maybe you're replaying events before the snapshot save has been confirmed.

**Comment by suganthkumar** [comment]
@Horusiath it makes sense to me on the Metadata table.

I have tested this multiple times, and confirmed that when I use Hyperion serializer the snapshots are getting created but not played back - but i get the events after the snapshots. 

When i switched back to default serializer Newtonsoft, i am receiving the snapshot playback too. I am not sure what is getting changed in this. but this is what happens.

i was using the atleast once delivery semantics example you provided in the gist
https://gist.github.com/Horusiath/64d829720b66df16bc59dbf106a8008e

**Comment by Horusiath** [comment]
@suganthkumar when you're making snapshots, the state you're providing is essentially serialized using the serialization logic you've specified for the type of your state. When you're replying it, state binary is taken back from the database, deserialized and passed to an actor.

So if you've serialized your snapshot with json.net and then you're trying to deserialize it with hyperion, then for sure you may hit an error. The simplest solution would be to add serialization binding in form of `"MyNameSpace.MyType,MyAssembly" = json` where the first part is fully qualified type name with assembly to the type of the state you've defined.
