### ISSUE TITLE
Ensuring that important PRs are merged before Akka Persistence is released

### ISSUE THREAD

**Issue by object** [akkadotnet/Akka.Persistence.SqlServer#67]
Akka.NET Persistence is still in beta but AFAIK is planned for RTM during the summer. There are some PRs that are important to merge before the release, in particular #59 and #60.

#59 doesn't affect anything at runtime, it's about consistend and deterministic names.
#60 is quite important, we had to fork Akka.Persistence.SqlServer to apply it, otherwise streaming AllEventsByTag don't work properly.

Both PRs are shown as if they break the build but IMHO it's a false negative, they are good. Is there anything that can be done to ensure the pending PRs are applied before the release? Anything I could do?

**Comment by Horusiath** [comment]
@object thx, I've totally forgot about them. We need to rerun those tests and merge the changes. They also should be reflected in batching journal implementation.

**Comment by object** [comment]
Great. Just let me know if there are any problems with them and you need new PRs.

**Comment by object** [comment]
Resolved.
