### ISSUE TITLE
Need to implement JournalSerializationSpec

### ISSUE THREAD

**Issue by Danthar** [akkadotnet/Akka.Persistence.SqlServer#74]
Right now there is no implementation for the JournalSerializationSpec from the persistence TCK.
https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Persistence.TCK/Serialization/JournalSerializationSpec.cs

Before we take this plugin out of beta, all the TCK tests should be implementated in this plugin. 

Related:
https://github.com/akkadotnet/akka.net/issues/3019

**Comment by Horusiath** [comment]
I could do that after upgrading to 1.3 (I've got problems with VS2015 lately).
