### ISSUE TITLE
how to delete Metadata after deleting snapshot?

### ISSUE THREAD

**Issue by RyanGhd** [akkadotnet/Akka.Persistence.SqlServer#76]
I have an actor inherited from `ReceivePersistentActor`. 
It save snapshots and then deletes the old snapshots after saving snapshot is successfully done using the following method:
```
DeleteSnapshots(new SnapshotSelectionCriteria(@event.Metadata.SequenceNr - 1));
```
Looks like this method doesn't delete relevant metadata records from MetaData table.

Is there any way to delete those records from MetaData table?

akka packages:
```
  Akka                        1.2.0
  Akka.DI.AutoFac             1.0.8
  Akka.DI.Core                1.0.8
  Akka.Persistence            1.1.2.30-beta
  Akka.Persistence.Sql.Common 1.1.2.30-beta
  Akka.Persistence.SqlServer  1.1.1.7-beta
  Akka.Remote                 1.2.0
```

**Comment by Horusiath** [comment]
Metadata is associated with events not snapshots themselves. Currently there's no method in the API itself, that would allow to clean them up.

**Comment by PeymanGhadiri** [comment]
In my case the actor takes snapshot after processing each 100 events. 
So this is a sample of what I got in Metadata table:
```
PersistenceId,               SequenceNr
EventJournalProcessorActor,  34100
EventJournalProcessorActor,  34200
EventJournalProcessorActor,  34300
```
the actor has deleted snapshot 34100 and 34200.

Is it safe to delete first 2 records manually from Metadata table after deleting their relavant snapshots or there are other use cases for them than handling the snapshots?

**Comment by PeymanGhadiri** [comment]
My app has been working in production for 16 months. 
The following shows the number of records in each table:

```
plugin                                                             table name                  # of records
akka.persistence.journal.sql-server                 persistent-journal       94
akka.persistence.journal.sql-server                 metadata                    198,374
akka.persistence.snapshot-store.sql-server    persistent journal        1,990
```
The app has 1,990 persistent actor atm.
Those actors produced 198,374 metadata records. So each actor has roughly produced 100 records.
Akka needs the latest record for each actor to get the sequenceNr.
I'm not sure why it needs to keep other 99 records.
It would be great if somebody could explain that.

Also any help for cleaning up metadata table would be much appreciated.

**Comment by Horusiath** [comment]
HI @PeymanGhadiri , reducing amount of garbage would probably require only updating SQL query (to make it working on insert-or-update, instead of insert). In terms of cleaning up metadata table, query should probably look more or less like (could be probably optimized):

```sql
-- For each PersistenceId, delete all records except the one 
-- with a most recent (the highest) SequenceNr
DELETE FROM Metadata a
WHERE EXISTS (
    SELECT * FROM Metadata b
    WHERE b.PersistenceId = a.PersistenceId
    AND b.SequenceNr <> (SELECT MAX(SequenceNr) FROM Metadata c 
                         WHERE c.PersistenceId = b.PersistenceId)
)
```

**Comment by PeymanGhadiri** [comment]
thanks a lot @Horusiath. I really appreciate it mate.
I call ReceivePersistentActor.SaveSnapshot and I think that creates the metadata records.
Does "updating SQL query" in your comment refer to a feature request or I should change my code to do that?

**Comment by anilkumble** [comment]
Hi 
I am using Cassandra for persistence and am using deleteMessages() method to delete my persisted data.

But looks like this method doesn't delete relevant metadata records from MetaData table.

Do we have any api to delete them in Cassandra
