### ISSUE TITLE
Migration script syntax

### ISSUE THREAD

**Issue by amichel** [akkadotnet/Akka.Persistence.SqlServer#87]
Migration script to v 1.3.2 syntax should be:
ALTER TABLE dbo.EventJournal **ADD SerializerId** INTEGER NULL
ALTER TABLE dbo.SnapshotStore **ADD SerializerId** INTEGER NULL
instead of **ADD COLUMN SerializerId**

**Comment by Aaronontheweb** [comment]
@amichel ah, thanks!
