### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by Havret** [akkadotnet/Akka.Persistence.SqlServer#94]
While trying to fix #91 I've noticed that there are quite a few tests which are failing in an indeterministic way. Here are some tests results which I got after pulling this repo and trying to run the tests. For the record, I am not using SQL Express but SQL Server 2017 (it shouldn't be a case anyway).

https://gist.github.com/Havret/54b8e2c0dde512ea727dd159b3bb70b7

**Comment by Aaronontheweb** [comment]
> Failed: Expected a message of type Akka.Persistence.RecoverySuccess, but received {ReplayMessagesFailure<cause: System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'dbo.EventJournal'.

Does this look like a configuration issue of some kind? Or is the `EventJournal` not yet created at this stage in the test for some reason?
